### PR TITLE
Pipeline waits for last child only

### PR DESCRIPTION
**Pull request by lsimonne**
fix cat /dev/urandom | head -c 10 => only wait for last child then kill all other children with SIGINT
(+ necessary simple handling of ctrl-c)

- problem: with refresh_line in editor, (last) output line is deleted. 
- quick fix here: changed first refresh_line to put_line (did it break anything @pilespin?), but still deletes line as soon as you type again
- alternative: putchar_fd('\n', 2) in wait_for_childs in case of SIGINT
problems with this solution: cat /dev/urandom | foo => prints a \n where it shouldn't (after error message) + no output if redirect stderr (cat /dev/urandom 2>test | head -c 10)

=> which do you think is best? any other idea?

### CODE REVIEW

**Comment by M5oul** [comment]
`Ctrl + C` works.
I can't test `cat /dev/urandom`. My terminal crash.

**Comment by lsimonne** [comment]
oh, why's that? base64 /dev/urandom too ?

(keep in mind that ctrl-c still needs to be implemented in the editor to delete the current line and display the prompt again)

**Comment by M5oul** [comment]
It even crash on other shells. It's not a problem.
Just to say that I won't be able to review this one.

**Comment by lsimonne** [comment]
yes, I get that it's not a code problem, just wondering if there was a way around it!

**Comment by M5oul** [comment]
ah. Yep, `base64` works.
I will review it.

**Pull request merged**
