### PR TITLE
handle conversion to relative path in cd

### PR DESCRIPTION
**Pull request by n0izn0iz**
#226 

> If curpath is longer than {PATH_MAX} bytes (including the terminating null) and the directory operand was not longer than {PATH_MAX} bytes (including the terminating null), then curpath shall be converted from an absolute pathname to an equivalent relative pathname if possible. This conversion shall always be considered possible if the value of PWD, with a trailing <slash> added if it does not already have one, is an initial substring of curpath. Whether or not it is considered possible under other circumstances is unspecified. Implementations may also apply this conversion if curpath is not longer than {PATH_MAX} bytes or the directory operand was longer than {PATH_MAX} bytes.

/pwd/some/path/too/long -> some/path/too/long

http://pubs.opengroup.org/onlinepubs/9699919799/utilities/cd.html

### CODE REVIEW

**Comment by n0izn0iz** [comment]
Je met la PR mais a mon avis on devrait ignorer cette partie de POSIX puisque PATH_MAX fait aucun sens si j'ai bien compris

**Comment by n0izn0iz** [comment]
Bon bah voila, c'est posix compliant et testé avec cunit

**Comment by pilespin** [comment]
quand je fais un cd d'un PATH absolu de len(4785)
42sh: cd: File name too long

**Comment by n0izn0iz** [comment]
je vois pas comment c'est possible
```
if (ret == -1)
	print_errno_error(errno, "cd", curpath);
else if (opt != 'P')
{
	set_variable("OLDPWD", current_pwd, true);
```
si ça print une erreur, ça peux pas set OLDPWD (else if)

**Comment by pilespin** [comment]
exact il est chelou mon OS

**Pull request merged**
